# @package _global_
# Hyperparameter search for BNN_Forces_Hetero (LRT guide)

defaults:
  - /hpsearch/study: study
  - /hpsearch/objective: bnn_hetero
  - override /experiment: bnn_lrt_hetero

hpsearch:
  monitor: total_rmse/val
  n_trials: 30
  study:
    study_name: bnn_lrt_hetero

trainer:
  max_epochs: 3000
  min_epochs: 100

callbacks:
  early_stopping:
    monitor: total_rmse/val
    patience: 50
    mode: min

tags: ["bayesian", "lrt", "hetero", "hps"]
