# @package _global_

defaults:
  - /hpsearch/study: study
  - /hpsearch/objective: hnn
  - override /experiment: hnn

hpsearch:
  monitor: nll/val
  study:
    study_name: hnn

trainer:
  max_epochs: 20
