# @package _global_

defaults:
  - /hpsearch/study: study
  - /hpsearch/objective: mcd
  - override /experiment: mcd

hpsearch:
  monitor: nll/val
  study:
    study_name: mcd

trainer:
  max_epochs: 20
