# @package _global_
# Hyperparameter search for Partial Radial (First Layer) with Forces

defaults:
  - /hpsearch/study: study
  - /hpsearch/objective: partial_bnn_forces
  - override /experiment: partial_rad_first_forces

hpsearch:
  monitor: total_rmse/val
  n_trials: 30
  study:
    study_name: partial_rad_first_forces

trainer:
  max_epochs: 3000
  min_epochs: 100

callbacks:
  early_stopping:
    monitor: total_rmse/val
    patience: 50
    mode: min

tags: ["partial_bayesian", "radial", "first", "forces", "hps"]
