# @package _global_

defaults:
  - _self_
  - prediction: dataset
  - trainer: cpu
  - paths: default
  - hydra: default

task_name: predict
run_name: default
tags: ["dev"]
subsets: ["val"]
ckpt_path: all
seed: null
