defaults:
  - net

_target_: bnn_aenet.models.bnn_forces.BNN_Forces

name: BNN_Forces

lr: 0.0001
pretrain_epochs: 0
mc_samples_train: 2
mc_samples_eval: 20
dataset_size: ??? # Set by datamodule
fit_context: lrt
guide: normal
prior_loc: 0
prior_scale: 0.1
q_scale: 0.001
obs_scale: 0.5
scale_force: 0.1
grad_clip_val: 1.0
