net:
  _target_: bnn_aenet.models.nets.heteroskedastic_network.NetAtom
  input_size: ???
  hidden_size: ???
  species: ???
  active_names: ???
  alpha: ???
  device: "cpu"
  e_scaling: ???
  e_shift: ???

_target_: bnn_aenet.models.hnn.HNN
p_dropout: 0
mc_samples: 0

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.001