defaults:
  - net

_target_: bnn_aenet.models.nn.NN

# Model name
name: NN

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001

alpha: 0.1  # Weight for force loss: (1-alpha)*E_loss + alpha*F_loss (FIXED)
