model:
  net:
    _target_: bnn_aenet.models.nets.heteroskedastic_network.NetAtom
    input_size:
    - 70
    - 70
    hidden_size:
    - - 15
      - 15
    - - 15
      - 15
    species:
    - Ti
    - O
    active_names:
    - - tanh
      - tanh
    - - tanh
      - tanh
    alpha: 0.0
    device: cpu
    e_scaling: 0.06565926932648217
    e_shift: 6.6588702845000975
  _target_: bnn_aenet.models.bnn.BNN
  lr: 0.0005377740280800115
  pretrain_epochs: 0
  mc_samples_train: 2
  mc_samples_eval: 20
  dataset_size: 6252
  fit_context: flipout
  guide: normal
  prior_loc: 0
  prior_scale: 0.05115252308821134
  q_scale: 0.008638033920872413
  obs_scale: 0.6127231816537825
model/params/total: 2674
model/params/trainable: 2674
model/params/non_trainable: 0
datamodule:
  _target_: bnn_aenet.datamodule.aenet_datamodule.AenetDataModule
  data_dir: /home/g15farris/bin/bayesaenet/data//TiO/train.in
  device: cpu
  batch_size: 64
  test_split: 0.1
  valid_split: 0.1
trainer:
  _target_: lightning.pytorch.trainer.Trainer
  default_root_dir: /home/g15farris/bin/bayesaenet/bnn_aenet/logs/TiO_hps_fo/runs/2025-02-19_15-52-25/022
  min_epochs: 20000
  max_epochs: 20
  accelerator: cpu
  devices: 1
  check_val_every_n_epoch: 1
  deterministic: false
callbacks:
  model_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: /home/g15farris/bin/bayesaenet/bnn_aenet/logs/TiO_hps_fo/runs/2025-02-19_15-52-25/022/checkpoints
    filename: epoch_{epoch}-step_{step}
    monitor: elbo/val
    verbose: false
    save_last: true
    save_top_k: 1
    mode: min
    auto_insert_metric_name: false
    save_weights_only: false
    every_n_train_steps: null
    train_time_interval: null
    every_n_epochs: null
    save_on_train_epoch_end: null
  rich_progress_bar:
    _target_: lightning.pytorch.callbacks.RichProgressBar
  model_summary:
    _target_: lightning.pytorch.callbacks.RichModelSummary
    max_depth: -1
  optuna_pruner:
    _target_: optuna.integration.PyTorchLightningPruningCallback
  early_stopping: null
extras: null
task_name: TiO_hps_fo
tags:
- TiO
ckpt_path: null
seed: 12345
